### ISSUE TITLE
Make F10 work everywhere

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-assembly#31] opened 2019-06-01 15:30 UTC
Right now the F10 key to show the mod flags only works in some places but doesn't work on main menu, config screen etc. Would it be possible to fix it so that it works everywhere? In some cases people can get stuck with this overlay on without an ability to hide it.

**Comment by drojf** [comment] 2020-07-21 11:15
Just reporting another (very easy) way to get stuck - open the menu, then click or highlight any text on the menu. 

This causes your cursor to appear on the text, and from then on, all keyboard input will be redirected to the textbox (including the F10 button). This prevents you from closing the menu until you deselect the text by clicking on the empty space on the right hand side to deselect it.

I should note that no matter how badly the menu gets stuck, as a player you can always save the game, then restart the game, and it will disappear, so the issue isn't that bad.

**Comment by drojf** [comment] 2021-01-20 09:50
Fixed in PR #53 :
 - You can open the F10 menu at any time
 - Clicking on the mod menu won't grab focus, so you can still close the mod menu even if you click on most things
   - There is one textbox on the mod menu, and if it has focus, you can't close the mod menu with F10, but you can either click the `X` button, or right click to close the mod menu. You can also click anywhere else on the menu to get it working again.

**Closed by drojf** 2021-01-20 09:50 UTC
Labels: enhancement
