### ISSUE TITLE
History Screen Replays Voices on Right Click

### ISSUE THREAD

**Issue by ghost** [07th-mod/higurashi-assembly#40] opened 2019-08-20 03:13 UTC
Report from player.  Right click is supposed to just close the history window.

> ~~are replayed lines supposed to be repeated at closing the textlog? sometimes it doesn't appear, but when it does, reopening and closing the textlog again also causes it to repeat. not the case when the line is scrolled up and out of sight. is this a feature?~~
> it will also play if you close the log pointing at a line, which isn't as bad as the former
> for that last case are you clicking the close button still or are you pressing escape with your mouse over a previous line
> the second? I right click
> the first doesn't require highlighting anything
> nevermind, both cases were the right click

From @tellowkrinkle 
> Ahh yeah the onClick probably doesn't differentiate between what type of click it was

**Comment by drojf** [comment] 2022-08-26 02:22
Can't reproduce this on Onikakushi, so I'm assuming this is fixed now.

**Closed by drojf** 2022-08-26 02:22 UTC
Labels: bug
